name: test_app_for_red
description: "Scan QR-code for rent portable charger"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.1.0
  go_router: ^16.1.0
  hooks_riverpod: ^2.6.1
  intl: ^0.20.2
  logging: ^1.3.0
  mobile_scanner: ^7.0.1
  pay: ^3.2.1
  retrofit: ^4.4.2
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5
  retrofit_generator: ^9.7.0
  flutter_lints: ^6.0.0
  freezed: ^3.1.0
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/fonts/Inter/
    - assets/fonts/SFProDisplay/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Light.otf
          weight: 300
    - family: San Francisco Pro Display
      fonts:
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Light.otf
          weight: 300
  
